import type { NextPage } from 'next';
import Head from 'next/head';
import { Footer } from '@components/Footer';
import { FloorPlanner } from '@components/FloorPlanner';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-[100vh] flex-1 flex-col items-center justify-center">
      <FloorPlanner />
    </main>
    <Footer />
  </>
);

export default Home;
