import type { NextPage } from 'next';
import Head from 'next/head';
import { Footer } from '@components/Footer';

const Home: NextPage = () => (
  <div className="px-8">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-[100vh] flex-1 flex-col items-center justify-center py-16"></main>

    <Footer />
  </div>
);

export default Home;
